### PR TITLE
fixed some typos

### PR DESCRIPTION
**Pull request by blairconrad**
"scowered" also slowed me down a bit, as "scoured" is traditional, but I see it is indeed an archaic form, and I'm all about vocabulary either from the future or the distant past!

### CODE REVIEW

**Comment by blairconrad** [comment]
Lemme tell you, tracking this repo down was not as easy as I thought it would be! You nearly got a PR over at jchannon.github.com…

**Comment by jchannon** [comment]
Thanks :)

**Comment by blairconrad** [comment]
A pleasure. Besides, it boosts [my score over at 24 Pull Requests](http://24pullrequests.com/users/blairconrad).

**Comment by jchannon** [comment]
ha ha!

**Pull request merged**
